import React from 'react';
import Navbar from '../src/app/components/Navbar';
import Footer from '../src/app/components/Footer';
import './globals.css'; // Assurez-vous d'importer vos styles globaux si nécessaire

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
